"""
Django settings for serverpanaccess project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
from pathlib import Path
from celery.schedules import crontab, timedelta
from dotenv import load_dotenv
from appConfig import (
    CacheConfig,
    CeleryConfig,
    CorsConfig,
    DatabaseConfig,
    DjangoConfig,
    EmailConfig,
    JwtConfig,
    PanaccessConfig,
    RedisConfig,
    SentryConfig,
    SocialConfig,
    StaticConfig,
    ThrottleConfig,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env (si existe)
load_dotenv(BASE_DIR / '.env')

# Configurar encoding UTF-8 para Windows
if sys.platform == 'win32':
    # Forzar UTF-8 en stdout/stderr para Windows
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    if hasattr(sys.stderr, 'reconfigure'):
        sys.stderr.reconfigure(encoding='utf-8', errors='replace')

# Validar las configuraciones
DjangoConfig.validate()
SocialConfig.validate()
PanaccessConfig.validate()
if DatabaseConfig.use_postgresql():
    DatabaseConfig.configure()
RedisConfig.validate()
CorsConfig.validate_no_allow_all()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

#* SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DjangoConfig.SECRET_KEY

#* SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DjangoConfig.DEBUG

# Hosts permitidos desde .env (ej. ALLOWED_HOSTS=localhost,127.0.0.1 — sin * en prod)
ALLOWED_HOSTS = DjangoConfig.ALLOWED_HOSTS or ['localhost', '127.0.0.1']

# HTTPS terminado en nginx (roadmap #3 / #5). PRODUCTION_HTTPS=true en Ubuntu con TLS.
PRODUCTION_HTTPS = DjangoConfig.PRODUCTION_HTTPS
if PRODUCTION_HTTPS and not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Rutas sync/admin solo desde estas IPs (roadmap #5). Vacío = sin filtro Django (usar nginx).
# Ejemplo: SYNC_ADMIN_IP_ALLOWLIST=127.0.0.1,10.8.0.0/24
SYNC_ADMIN_IP_ALLOWLIST = DjangoConfig.SYNC_ADMIN_IP_ALLOWLIST


# ============================================================================
# APLICACIONES INSTALADAS
# ============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'wind',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ============================================================================
# MIDDLEWARE
# ============================================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise: servir archivos estáticos (incluye imágenes) en producción
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

if SYNC_ADMIN_IP_ALLOWLIST:
    MIDDLEWARE.insert(
        1,
        "wind.middleware.sync_admin_ip_middleware.SyncAdminIPRestrictionMiddleware",
    )

# Permitir que el popup de Google Sign-In se comunique con nuestra ventana
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# ============================================================================
# CORS (frontend separado del backend)
# ============================================================================
CORS_ALLOWED_ORIGINS = CorsConfig.resolved_origins(debug=DEBUG)
CORS_ALLOW_CREDENTIALS = CorsConfig.ALLOW_CREDENTIALS

# Preflight: cubre métodos/headers típicos de APIs JSON + Authorization
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# ============================================================================
# CONFIGURACIÓN DE REST FRAMEWORK
# ============================================================================
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        # Endurecido: todo endpoint debe ser explícito si es público.
        # Usar AllowAny solo donde corresponda (registro/login público, health si fuese DRF, etc.)
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'wind.throttles.AnonBurstThrottle',
        'wind.throttles.UserBurstThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': ThrottleConfig.ANON,
        'user': ThrottleConfig.USER,
        'profile': ThrottleConfig.PROFILE,
        'sync_admin': ThrottleConfig.SYNC_ADMIN,
        'register': ThrottleConfig.REGISTER,
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ============================================================================
# JWT y DJ-REST-AUTH: Autenticación de sesiones de cliente
# ============================================================================
from datetime import timedelta

REST_AUTH = {
    'USE_JWT': True,
    'USER_DETAILS_SERIALIZER': 'wind.serializers.JWTUserDetailsSerializer',
    'LOGIN_SERIALIZER': 'wind.auth_serializers.PanAccessLoginSerializer',
}

# Preferimos Authorization: Bearer. Cookies JWT solo si el front lo requiere explícitamente.
if JwtConfig.USE_COOKIES:
    REST_AUTH.update(
        {
            "JWT_AUTH_COOKIE": JwtConfig.AUTH_COOKIE,
            "JWT_AUTH_REFRESH_COOKIE": JwtConfig.REFRESH_COOKIE,
        }
    )

SIMPLE_JWT = {
    # Prod: 5–15 min recomendado. Dev: puede ser más largo.
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=max(1, JwtConfig.access_minutes(debug=DEBUG)),
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=JwtConfig.REFRESH_DAYS),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ============================================================================
# ALLAUTH: Autenticación y flujos sociales
# ============================================================================
SITE_ID = 1
# Django 6 / django-allauth: preferir ACCOUNT_LOGIN_METHODS y ACCOUNT_SIGNUP_FIELDS.
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

# ============================================================================
# EMAIL / ALLAUTH: verificación de email (prod) vs dev
# ============================================================================
# Default:
# - Dev (DEBUG=true): none (evita fallos si no hay SMTP)
# - Prod (DEBUG=false): mandatory (recomendado si hay registro por contraseña)
ACCOUNT_EMAIL_VERIFICATION = EmailConfig.account_verification(debug=DEBUG)
EMAIL_BACKEND = EmailConfig.resolved_backend(debug=DEBUG)
EMAIL_HOST = EmailConfig.HOST
EMAIL_PORT = EmailConfig.PORT
EMAIL_HOST_USER = EmailConfig.HOST_USER
EMAIL_HOST_PASSWORD = EmailConfig.HOST_PASSWORD
EMAIL_USE_TLS = EmailConfig.USE_TLS
DEFAULT_FROM_EMAIL = EmailConfig.DEFAULT_FROM

# Adaptador perzonalizado para conectar Google con PanAccess
SOCIALACCOUNT_ADAPTER = 'wind.adapters.PanAccessSocialAccountAdapter'


# ============================================================================
# URLs
# ============================================================================
ROOT_URLCONF = 'serverpanaccess.urls'

# ============================================================================
# TEMPLATES
# ============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'serverpanaccess.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Xampp MariaDB
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'wind',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': os.getenv("MYSQL_HOST", "127.0.0.1"),  # cambia a "db" si usas docker-compose
#         'PORT': os.getenv("MYSQL_PORT", "3307"),
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#         # Optimizaciones para mejor rendimiento con carga alta
#         'CONN_MAX_AGE': 1000,  # Mantener conexiones vivas por 5 minutos (reducir overhead)
#         'AUTOCOMMIT': True,
#     }
# }

# Base de datos: SQLite (dev) o PostgreSQL (staging/prod) vía DB_ENGINE en .env
if DatabaseConfig.use_postgresql():
    DATABASES = {'default': DatabaseConfig.django_default_database()}
    _replica = DatabaseConfig.django_replica_database()
    if _replica:
        DATABASES['replica'] = _replica
        DATABASE_ROUTERS = ['wind.db_router.PrimaryReplicaRouter']
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# CDN opcional (Fase 4): CDN_STATIC_URL=https://cdn.ejemplo.com/static/
STATIC_URL = ((StaticConfig.CDN_URL or '/static/').rstrip('/') + '/')

# En producción, Django NO sirve estáticos por defecto.
# WhiteNoise los sirve desde STATIC_ROOT luego de collectstatic.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: en DEBUG servir desde wind/static/ (finders), sin copia vieja en staticfiles/.
# En producción: collectstatic + manifest + hash para cache busting.
if DEBUG:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    # Sin esto, WhiteNoise prioriza staticfiles/ (p. ej. app.625403f0f035.css desactualizado).
    WHITENOISE_USE_FINDERS = True
else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# CELERY / REDIS (tareas asíncronas y programación)
# ============================================================================

REDIS_HOST = RedisConfig.HOST
REDIS_PORT = RedisConfig.PORT
REDIS_DB = RedisConfig.DB
REDIS_PASSWORD = RedisConfig.PASSWORD

CELERY_BROKER_URL = RedisConfig.broker_url()
CELERY_RESULT_BACKEND = RedisConfig.result_backend_url()
CELERY_TASK_ALWAYS_EAGER = RedisConfig.celery_eager()
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER
CELERY_TASK_TIME_LIMIT = CeleryConfig.TASK_TIME_LIMIT
CELERY_TASK_SOFT_TIME_LIMIT = CeleryConfig.TASK_SOFT_TIME_LIMIT
CELERY_WORKER_MAX_TASKS_PER_CHILD = CeleryConfig.WORKER_MAX_TASKS_PER_CHILD
CELERY_WORKER_POOL = CeleryConfig.WORKER_POOL
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = not CELERY_TASK_ALWAYS_EAGER
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = TIME_ZONE

# Configurar cola por defecto para tareas específicas
CELERY_TASK_ROUTES = {
    'wind.tasks.sync_subscribers_task': {'queue': 'sync_subscribers'},
    'wind.tasks.compare_and_update_subscribers_task': {'queue': 'sync_subscribers'},
    'wind.tasks.sync_smartcards_task': {'queue': 'sync_subscribers'},
    'wind.tasks.compare_and_update_smartcards_task': {'queue': 'sync_subscribers'},
    'wind.tasks.full_sync_task': {'queue': 'sync_subscribers'},
}

_SYNC_MINUTES = CeleryConfig.SYNC_MINUTES
_SYNC_LIMIT = CeleryConfig.SYNC_LIMIT
_SYNC_QUEUE = CeleryConfig.SYNC_QUEUE
_SMARTCARD_SYNC_MINUTES = CeleryConfig.SMARTCARD_SYNC_MINUTES

if CeleryConfig.USE_CRONTAB:
    _SCHEDULE = crontab(minute=f"*/{_SYNC_MINUTES}")
    _SMARTCARD_SCHEDULE = crontab(minute=f"*/{_SMARTCARD_SYNC_MINUTES}")
else:
    _SCHEDULE = timedelta(minutes=_SYNC_MINUTES)
    _SMARTCARD_SCHEDULE = timedelta(minutes=_SMARTCARD_SYNC_MINUTES)

_FULL_SYNC_HOUR = CeleryConfig.FULL_SYNC_HOUR
_FULL_SYNC_MINUTE = CeleryConfig.FULL_SYNC_MINUTE
_FULL_SYNC_TIME_LIMIT = CeleryConfig.FULL_SYNC_TIME_LIMIT
_FULL_SYNC_SOFT_LIMIT = CeleryConfig.FULL_SYNC_SOFT_TIME_LIMIT
_FULL_SYNC_ENABLED = CeleryConfig.FULL_SYNC_ENABLED

CELERY_BEAT_SCHEDULE = {
    # Tras carga manual en deploy (sync-subscribers HTTP); mantenimiento cada N min
    "compare-and-update-subscribers": {
        "task": "wind.tasks.compare_and_update_subscribers_task",
        "schedule": _SCHEDULE,
        "options": {
            "queue": _SYNC_QUEUE,
            "soft_time_limit": CELERY_TASK_SOFT_TIME_LIMIT,
            "time_limit": CELERY_TASK_TIME_LIMIT,
        },
        "args": (_SYNC_LIMIT,),
    },
    # Tras sync-smartcards HTTP en deploy; reconciliación (crear / actualizar / borrar)
    "compare-and-update-smartcards": {
        "task": "wind.tasks.compare_and_update_smartcards_task",
        "schedule": _SMARTCARD_SCHEDULE,
        "options": {
            "queue": _SYNC_QUEUE,
            "soft_time_limit": CELERY_TASK_SOFT_TIME_LIMIT,
            "time_limit": CELERY_TASK_TIME_LIMIT,
        },
        "args": (_SYNC_LIMIT,),
    },
}

if _FULL_SYNC_ENABLED:
    CELERY_BEAT_SCHEDULE["full-sync-nightly"] = {
        "task": "wind.tasks.full_sync_task",
        "schedule": crontab(hour=_FULL_SYNC_HOUR, minute=_FULL_SYNC_MINUTE),
        "options": {
            "queue": _SYNC_QUEUE,
            "soft_time_limit": _FULL_SYNC_SOFT_LIMIT,
            "time_limit": _FULL_SYNC_TIME_LIMIT,
        },
        "kwargs": {"limit": _SYNC_LIMIT},
    }

# ============================================================================
# CACHÉ REDIS (Fase 3) — DB distinta al broker Celery (REDIS_CACHE_DB)
# ============================================================================
REDIS_CACHE_DB = RedisConfig.CACHE_DB

if CacheConfig.USE_LOCMEM:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'wind-default',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': RedisConfig.build_url(db=REDIS_CACHE_DB),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        }
    }

# Sesión PanAccess compartida entre workers (requiere Redis)
PANACCESS_SESSION_USE_REDIS = PanaccessConfig.session_use_redis(
    celery_eager=CELERY_TASK_ALWAYS_EAGER,
)
PANACCESS_SESSION_TTL_SECONDS = PanaccessConfig.SESSION_TTL_SECONDS

# Circuit breaker PanAccess (Fase 4)
PANACCESS_CIRCUIT_BREAKER_ENABLED = PanaccessConfig.circuit_breaker_enabled(debug=DEBUG)
PANACCESS_CB_FAILURE_THRESHOLD = PanaccessConfig.CB_FAILURE_THRESHOLD
PANACCESS_CB_RECOVERY_SECONDS = PanaccessConfig.CB_RECOVERY_SECONDS

# ============================================================================
# SENTRY (Fase 3) — solo si SENTRY_DSN está definido
# ============================================================================
if SentryConfig.DSN:
    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=SentryConfig.DSN,
        integrations=[DjangoIntegration(), CeleryIntegration(), RedisIntegration()],
        traces_sample_rate=SentryConfig.TRACES_SAMPLE_RATE,
        send_default_pii=False,
        environment=SentryConfig.environment(debug=DEBUG),
    )

# ============================================================================
# CONFIGURACIÓN DE LOGGING
# ============================================================================

# Crear directorio de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'unicode_safe': {
            '()': 'wind.utils.logging_handlers.UnicodeSafeFilter',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            '()': 'wind.utils.logging_handlers.SafeConsoleHandler',
            'formatter': 'detailed',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'delay': True,
        },
        'panaccess_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'panaccess.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'delay': True,
        },
        'tasks_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'tasks.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'delay': True,
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'delay': True,
        },
    },
    'root': {
        # 'error_file' para concentrar trazas de errores de cualquier logger.
        'handlers': ['console', 'file', 'error_file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Opcional: SQL en DEBUG (suele ser muy ruidoso).
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'wind': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'wind.services.panaccess_singleton': {
            # También enviamos a django.log para ver el flujo completo
            # (create_subscriber + llamadas PanAccess) en un solo archivo.
            'handlers': ['console', 'file', 'panaccess_file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'wind.utils.panaccess_auth': {
            'handlers': ['console', 'file', 'panaccess_file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'wind.services.panaccess_client': {
            'handlers': ['console', 'file', 'panaccess_file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'wind.apps': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        # Celery / tareas
        'celery': {
            'handlers': ['console', 'tasks_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.worker': {
            'handlers': ['console', 'tasks_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.beat': {
            'handlers': ['console', 'tasks_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

_SOCIALACCOUNT_PROVIDERS_ALL = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'APP': {
            'client_id': SocialConfig.GOOGLE_CLIENT_ID,
            'secret': SocialConfig.GOOGLE_CLIENT_SECRET,
            'key': '',
        },
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': ['id', 'email', 'first_name', 'last_name', 'name'],
        'VERIFIED_EMAIL': False,
        'VERSION': 'v20.0',
        'APP': {
            'client_id': SocialConfig.FACEBOOK_APP_ID,
            'secret': SocialConfig.FACEBOOK_APP_SECRET,
            'key': '',
        },
    },
}

SOCIALACCOUNT_PROVIDERS = {
    name: _SOCIALACCOUNT_PROVIDERS_ALL[name]
    for name in SocialConfig.enabled_providers()
    if name in _SOCIALACCOUNT_PROVIDERS_ALL
}

# Redirección tras login/logout con Google (allauth)
LOGIN_REDIRECT_URL = '/wind/login-test/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/wind/login-test/'