"""
Django settings for serverpanaccess project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path
from celery.schedules import crontab, timedelta
from dotenv import load_dotenv
from appConfig import DjangoConfig, SocialConfig, DatabaseConfig, RedisConfig, _env_bool

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env (si existe)
load_dotenv(BASE_DIR / '.env')

# Configurar encoding UTF-8 para Windows
if sys.platform == 'win32':
    # Forzar UTF-8 en stdout/stderr para Windows
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    if hasattr(sys.stderr, 'reconfigure'):
        sys.stderr.reconfigure(encoding='utf-8', errors='replace')

# Validar las configuraciones
DjangoConfig.validate()
SocialConfig.validate()
if DatabaseConfig.use_postgresql():
    DatabaseConfig.configure()
RedisConfig.validate()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

#* SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DjangoConfig.SECRET_KEY

#* SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DjangoConfig.DEBUG

# Hosts permitidos desde .env (ej. ALLOWED_HOSTS=localhost,127.0.0.1 o * en dev)
ALLOWED_HOSTS = DjangoConfig.ALLOWED_HOSTS or ['localhost', '127.0.0.1']


# ============================================================================
# APLICACIONES INSTALADAS
# ============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'wind',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ============================================================================
# MIDDLEWARE
# ============================================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise: servir archivos estáticos (incluye imágenes) en producción
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Permitir que el popup de Google Sign-In se comunique con nuestra ventana
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# ============================================================================
# CORS (frontend separado del backend)
# ============================================================================
def _csv_env(name: str) -> list[str]:
    raw = os.getenv(name, "")
    return [x.strip() for x in raw.split(",") if x.strip()]


_CORS_ALLOWED_ORIGINS = _csv_env("CORS_ALLOWED_ORIGINS")
if not _CORS_ALLOWED_ORIGINS:
    # Sin variable en .env: orígenes típicos de front local (CRA :3000, Vite :5173).
    # En producción define CORS_ALLOWED_ORIGINS=https://tu-dominio.com (no dejes vacío si el front es otro host).
    _CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

CORS_ALLOWED_ORIGINS = _CORS_ALLOWED_ORIGINS

# Si necesitas cookies/sesión cross-site (no es el caso típico de JWT en header),
# habilita credenciales y asegúrate de NO usar CORS_ALLOW_ALL_ORIGINS=True con esto.
CORS_ALLOW_CREDENTIALS = os.getenv("CORS_ALLOW_CREDENTIALS", "false").lower() in ("true", "1", "yes")

# Preflight: cubre métodos/headers típicos de APIs JSON + Authorization
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# ============================================================================
# CONFIGURACIÓN DE REST FRAMEWORK
# ============================================================================
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'wind.throttles.AnonBurstThrottle',
        'wind.throttles.UserBurstThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('DRF_THROTTLE_ANON', '60/minute'),
        'user': os.getenv('DRF_THROTTLE_USER', '600/minute'),
        'profile': os.getenv('DRF_THROTTLE_PROFILE', '120/minute'),
        'sync_admin': os.getenv('DRF_THROTTLE_SYNC_ADMIN', '30/minute'),
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ============================================================================
# JWT y DJ-REST-AUTH: Autenticación de sesiones de cliente
# ============================================================================
from datetime import timedelta

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'wind-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'wind-refresh-token',
    'USER_DETAILS_SERIALIZER': 'wind.serializers.JWTUserDetailsSerializer',
    'LOGIN_SERIALIZER': 'wind.auth_serializers.PanAccessLoginSerializer',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ============================================================================
# ALLAUTH: Autenticación y flujos sociales
# ============================================================================
SITE_ID = 1
# Django 6 / django-allauth: preferir ACCOUNT_LOGIN_METHODS y ACCOUNT_SIGNUP_FIELDS.
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# Para flujos headless/mobile (REST) evitamos el envío de correos de verificación
# durante el login social. En desarrollo no hay SMTP configurado y esto provoca
# un 500 al intentar enviar confirmaciones.
ACCOUNT_EMAIL_VERIFICATION = 'none'

# Adaptador perzonalizado para conectar Google con PanAccess
SOCIALACCOUNT_ADAPTER = 'wind.adapters.PanAccessSocialAccountAdapter'


# ============================================================================
# URLs
# ============================================================================
ROOT_URLCONF = 'serverpanaccess.urls'

# ============================================================================
# TEMPLATES
# ============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'serverpanaccess.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Xampp MariaDB
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'wind',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': os.getenv("MYSQL_HOST", "127.0.0.1"),  # cambia a "db" si usas docker-compose
#         'PORT': os.getenv("MYSQL_PORT", "3307"),
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#         # Optimizaciones para mejor rendimiento con carga alta
#         'CONN_MAX_AGE': 1000,  # Mantener conexiones vivas por 5 minutos (reducir overhead)
#         'AUTOCOMMIT': True,
#     }
# }

# Base de datos: SQLite (dev) o PostgreSQL (staging/prod) vía DB_ENGINE en .env
if DatabaseConfig.use_postgresql():
    DATABASES = {'default': DatabaseConfig.django_default_database()}
    _replica = DatabaseConfig.django_replica_database()
    if _replica:
        DATABASES['replica'] = _replica
        DATABASE_ROUTERS = ['wind.db_router.PrimaryReplicaRouter']
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# CDN opcional (Fase 4): CDN_STATIC_URL=https://cdn.ejemplo.com/static/
_cdn_static = os.getenv('CDN_STATIC_URL', '').strip()
STATIC_URL = ((_cdn_static if _cdn_static else '/static/').rstrip('/') + '/')

# En producción, Django NO sirve estáticos por defecto.
# WhiteNoise los sirve desde STATIC_ROOT luego de collectstatic.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: en DEBUG servir desde wind/static/ (finders), sin copia vieja en staticfiles/.
# En producción: collectstatic + manifest + hash para cache busting.
if DEBUG:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    # Sin esto, WhiteNoise prioriza staticfiles/ (p. ej. app.625403f0f035.css desactualizado).
    WHITENOISE_USE_FINDERS = True
else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# CELERY / REDIS (tareas asíncronas y programación)
# ============================================================================

def _as_int(value, default):
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


REDIS_HOST = RedisConfig.HOST
REDIS_PORT = RedisConfig.PORT
REDIS_DB = RedisConfig.DB
REDIS_PASSWORD = RedisConfig.PASSWORD

CELERY_BROKER_URL = RedisConfig.broker_url()
CELERY_RESULT_BACKEND = RedisConfig.result_backend_url()
CELERY_TASK_ALWAYS_EAGER = RedisConfig.celery_eager()
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER
CELERY_TASK_TIME_LIMIT = _as_int(os.getenv("CELERY_TASK_TIME_LIMIT", "600"), 600)          # hard limit
CELERY_TASK_SOFT_TIME_LIMIT = _as_int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", "540"), 540)  # aviso previo
CELERY_WORKER_MAX_TASKS_PER_CHILD = _as_int(os.getenv("CELERY_WORKER_MAX_TASKS_PER_CHILD", "100"), 100)
# Windows: pool "solo" (prefork falla). Linux: "prefork". Override con CELERY_WORKER_POOL.
CELERY_WORKER_POOL = RedisConfig.celery_worker_pool()
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = not CELERY_TASK_ALWAYS_EAGER
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = TIME_ZONE

# Configurar cola por defecto para tareas específicas
CELERY_TASK_ROUTES = {
    'wind.tasks.sync_subscribers_task': {'queue': 'sync_subscribers'},
    'wind.tasks.sync_smartcards_task': {'queue': 'sync_subscribers'},
    'wind.tasks.full_sync_task': {'queue': 'sync_subscribers'},
}

_SYNC_MINUTES = max(1, _as_int(os.getenv("CELERY_SYNC_MINUTES", "10"), 10))
_SYNC_LIMIT = max(1, _as_int(os.getenv("CELERY_SYNC_LIMIT", "200"), 200))
_SYNC_QUEUE = os.getenv("CELERY_SYNC_QUEUE", "sync_subscribers")

# Configuración para smartcards (puede tener intervalo diferente)
_SMARTCARD_SYNC_MINUTES = max(1, _as_int(os.getenv("CELERY_SMARTCARD_SYNC_MINUTES", "10"), 10))

# Usar timedelta para schedule más predecible (cada X minutos desde el inicio)
# Alternativamente puedes usar crontab para ejecutar en minutos específicos
_USE_CRONTAB = os.getenv("CELERY_USE_CRONTAB", "false").lower() == "true"

if _USE_CRONTAB:
    # Modo crontab: ejecuta en minutos múltiplos de _SYNC_MINUTES (ej: */10 = 0, 10, 20, 30, 40, 50)
    _SCHEDULE = crontab(minute=f"*/{_SYNC_MINUTES}")
    _SMARTCARD_SCHEDULE = crontab(minute=f"*/{_SMARTCARD_SYNC_MINUTES}")
else:
    # Modo timedelta: ejecuta cada X minutos desde el inicio de Beat
    _SCHEDULE = timedelta(minutes=_SYNC_MINUTES)
    _SMARTCARD_SCHEDULE = timedelta(minutes=_SMARTCARD_SYNC_MINUTES)

_FULL_SYNC_HOUR = max(0, min(23, _as_int(os.getenv("CELERY_FULL_SYNC_HOUR", "0"), 0)))
_FULL_SYNC_MINUTE = max(0, min(59, _as_int(os.getenv("CELERY_FULL_SYNC_MINUTE", "0"), 0)))
_FULL_SYNC_TIME_LIMIT = max(600, _as_int(os.getenv("CELERY_FULL_SYNC_TIME_LIMIT", "3600"), 3600))
_FULL_SYNC_SOFT_LIMIT = max(540, _as_int(os.getenv("CELERY_FULL_SYNC_SOFT_TIME_LIMIT", "3300"), 3300))
_FULL_SYNC_ENABLED = os.getenv("CELERY_FULL_SYNC_ENABLED", "true").lower() in ("true", "1", "yes")

CELERY_BEAT_SCHEDULE = {
    "sync-subscribers": {
        "task": "wind.tasks.sync_subscribers_task",
        "schedule": _SCHEDULE,
        "options": {
            "queue": _SYNC_QUEUE,
            "soft_time_limit": CELERY_TASK_SOFT_TIME_LIMIT,
            "time_limit": CELERY_TASK_TIME_LIMIT,
        },
        "args": (_SYNC_LIMIT,),
    },
    "sync-smartcards": {
        "task": "wind.tasks.sync_smartcards_task",
        "schedule": _SMARTCARD_SCHEDULE,
        "options": {
            "queue": _SYNC_QUEUE,
            "soft_time_limit": CELERY_TASK_SOFT_TIME_LIMIT,
            "time_limit": CELERY_TASK_TIME_LIMIT,
        },
        "args": (_SYNC_LIMIT,),
    },
}

if _FULL_SYNC_ENABLED:
    CELERY_BEAT_SCHEDULE["full-sync-nightly"] = {
        "task": "wind.tasks.full_sync_task",
        "schedule": crontab(hour=_FULL_SYNC_HOUR, minute=_FULL_SYNC_MINUTE),
        "options": {
            "queue": _SYNC_QUEUE,
            "soft_time_limit": _FULL_SYNC_SOFT_LIMIT,
            "time_limit": _FULL_SYNC_TIME_LIMIT,
        },
        "kwargs": {"limit": _SYNC_LIMIT},
    }

# ============================================================================
# CACHÉ REDIS (Fase 3) — DB distinta al broker Celery (REDIS_CACHE_DB)
# ============================================================================
REDIS_CACHE_DB = max(0, min(15, _as_int(os.getenv('REDIS_CACHE_DB', '1'), 1)))
_CACHE_USE_LOCmem = os.getenv('CACHE_BACKEND', '').lower() == 'locmem'

if _CACHE_USE_LOCmem:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'wind-default',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': RedisConfig.build_url(db=REDIS_CACHE_DB),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        }
    }

# Sesión PanAccess compartida entre workers (requiere Redis)
PANACCESS_SESSION_USE_REDIS = _env_bool(
    'PANACCESS_SESSION_USE_REDIS',
    default=not CELERY_TASK_ALWAYS_EAGER,
)
PANACCESS_SESSION_TTL_SECONDS = max(
    300, _as_int(os.getenv('PANACCESS_SESSION_TTL_SECONDS', '1500'), 1500)
)

# Circuit breaker PanAccess (Fase 4)
PANACCESS_CIRCUIT_BREAKER_ENABLED = _env_bool(
    'PANACCESS_CIRCUIT_BREAKER_ENABLED',
    default=not DEBUG,
)
PANACCESS_CB_FAILURE_THRESHOLD = max(
    1, _as_int(os.getenv('PANACCESS_CB_FAILURE_THRESHOLD', '5'), 5)
)
PANACCESS_CB_RECOVERY_SECONDS = max(
    10, _as_int(os.getenv('PANACCESS_CB_RECOVERY_SECONDS', '60'), 60)
)

# ============================================================================
# SENTRY (Fase 3) — solo si SENTRY_DSN está definido
# ============================================================================
_SENTRY_DSN = os.getenv('SENTRY_DSN', '').strip()
if _SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        integrations=[DjangoIntegration(), CeleryIntegration(), RedisIntegration()],
        traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        send_default_pii=False,
        environment=os.getenv('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development'),
    )

# ============================================================================
# CONFIGURACIÓN DE LOGGING
# ============================================================================

# Crear directorio de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'unicode_safe': {
            '()': 'wind.utils.logging_handlers.UnicodeSafeFilter',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            '()': 'wind.utils.logging_handlers.SafeConsoleHandler',
            'formatter': 'detailed',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'panaccess_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'panaccess.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'wind': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'wind.services.panaccess_singleton': {
            'handlers': ['console', 'panaccess_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'wind.utils.panaccess_auth': {
            'handlers': ['console', 'panaccess_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'wind.services.panaccess_client': {
            'handlers': ['console', 'panaccess_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'wind.apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
    },
}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'APP': {
            'client_id': SocialConfig.GOOGLE_CLIENT_ID,
            'secret': SocialConfig.GOOGLE_CLIENT_SECRET,
            'key': '',
        },
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': ['id', 'email', 'first_name', 'last_name', 'name'],
        'VERIFIED_EMAIL': False,
        'VERSION': 'v20.0',
        'APP': {
            'client_id': SocialConfig.FACEBOOK_APP_ID,
            'secret': SocialConfig.FACEBOOK_APP_SECRET,
            'key': '',
        },
    },
    'apple': {
        'APPS': {
            'client_id': SocialConfig.APPLE_CLIENT_ID,
            'secret': SocialConfig.APPLE_CLIENT_SECRET,
            'key': "",
        },
    },
}

# Redirección tras login/logout con Google (allauth)
LOGIN_REDIRECT_URL = '/wind/login-test/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/wind/login-test/'