# Generated by Django 6.0.5 on 2026-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberlogininfo',
            name='login1',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberlogininfo',
            name='login2',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberlogininfo',
            name='subscriberCode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
